### ISSUE TITLE
Database - Data Model

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#11]
As a developer, I need a Data Model so that  information structure can be implemented in a Database.

**Acceptance Criteria** 

- Data model has been selected to response to the app's purpose
- ER model has been drawn

**Tasks**

- [x] Mapping out the main entities, relationships and attributes
- [x] Decide actual database schema and associate tables with columns
- [x]  ER model  has been designed
- [x] Describe the data schema fully in the README file
