### ISSUE TITLE
Admin. manage Persona, Comment, Likes

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#13]
As a Site Owner, I want to be able to create, read, update and delete postcards, so that I can control the content of the app

**Acceptance criteria**

Admin dashboard has been properly set up in oder to manage postcard and comment

**Tasks**

- [x] Create a superuser
- [x] Import the persona, like, comment and contactForm models  : 
         In placard/admin.py  >>  from .models import *
         In contact/admin.py  >>  from .models import *

- [x] Add method include  to wall_of_shame/urls in order to be able to use summernote app : 

       from djanngo.urls import path; include
       add path to django_summernote.urls

- [x] Import SummernoteModelAdmin to Admin.py
- [x] Building the admin panel : 

       Create  class PersonaAdmin, CommentAdmin, LikeAdmin and ContactFormAdmin
       Use decorator

- [x] CRUD Functionality efficient from panel admin
