### ISSUE TITLE
PersonaList

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#15]
As a User , I want to be able to see a list of Persona, so that I can select one.

**Acceptance criteria**

- A list of persona has been displayed
- Pagination has been set

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
