### ISSUE TITLE
PersonaDetails

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#16]
As a User , I want to be able to click on one persona of a list , so that I can open it and access/read its details

**Acceptance criteria**

- A persona details has been displayed

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
