### ISSUE TITLE
header

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#18]
As a user I want to be able to have intuitive User Interface so that I can  easily navigate

**Acceptance criteria**

- A Navbar has been displayed with identified links to suit the navigation

**Tasks**

- [x] Bootstrap core  responsive design
- [x] Personalise placement of the items
- [x] style links
- [x] django tags to differentiate navbar for  visitors from  authenticated users
