### ISSUE TITLE
Installing Django and supporting libraries

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#2]
As de developer, I need to install Django framework so that  a project and an app can be created

**Acceptance Criteria**

Django 3.2 (Long Term Support) has to been installed
a txt file listing all the dependencies for Python project has been created

**Tasks**

- [x] Install Django and gunicorn: pip3 install 'django<4' gunicorn
- [x] Install supporting libraries: pip3 install dj_database_url psycopg2
- [x] Install Cloudinary Libraries: pip3 install dj3-cloudinary-storage
- [x] Install crispy_forms : pip3 install crispy-bootstrap5
- [x] Install summernote:  pip3 install  django-summernote
- [x] Create requirements file: pip3 freeze --local > requirements.txt
