### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#22]
As a user, I want to be able to search word, so that I can find Persona associated with some keywords

**Acceptance criteria**

A effective search field  is included to the navbar

**Tasks**

- [x] Create a view
- [x] Create a template - take persona_list  template as structure
- [x] Create an url 
- [x] Connect url in form
