### ISSUE TITLE
User's page

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#25]
As a user, I want to be able to see all my Personas in one page, so that I can easily control my content.

**Acceptance criteria**

- A page with all user's personas has been display

**Tasks**

- [ ] Create the model
- [ ] Create  the view code ( class-based views)
- [ ] Create a template to render the view
- [ ] Connect URLs  in the urls.py file
