### ISSUE TITLE
like/unlike

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#26]
As a user, I want to be able to like or unlike, so that I can show my appreciation of another user's persona

**Acceptance criteria**

- A  number of likes display is associated to a Persona

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Modify PersonaDetail template to render the view
- [x] Connect URLs  in the urls.py file
