### ISSUE TITLE
Create Persona

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#27]
As a user, I want to be able to create a persona, so that I can share my own persona with the others

**Acceptance criteria**

A form has been displayed with fields that allow input in order to create a persona

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
- [x] Create a form
