### ISSUE TITLE
Delete Persona

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#29]
As a user, I want to be able to delete a persona, so that I can decide which content stay in the site.

**Acceptance criteria**

A delete page has been displayed with btn to execute action

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
- [x] Create a form
