### ISSUE TITLE
Start a project and create an app

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#3]
As a developer, I need to create the base setup of the application so other features can be added.

**Acceptance Criteria**

- The application has been created (Run Server to Test: python3 manage.py runserver)
- Secret key is not pushed with the application
- Settings for development and production have been specified in the settings.py

**Tasks**

- [x] Create Project : django-admin startproject PROJ_NAME .
- [x] Create Apps: python3 manage.py startapp APP_NAME
- [x] Add to installed apps
- [x] Save file
- [x] Migrate Changes: python3 manage.py migrate
