### ISSUE TITLE
update Persona

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Wall_of_Shame#30]
As a user, I want to be able to update my persona, so that I can share modify my published content

**Acceptance criteria**

A form has been displayed with fields that allow input in order to create a persona

**Tasks**

- [x] Create  the view code ( class-based views)
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
- [x] Create a form
